// <auto-generated />
using System;
using LibraryConnection.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030232334_NombreDeLaMigracion")]
    partial class NombreDeLaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryConnection.DbSet.Client", b =>
                {
                    b.Property<string>("document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("docType")
                        .HasColumnType("text");

                    b.Property<string>("emailAddress")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("document");

                    b.ToTable("clients", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.Property<string>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("customer_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<double>("total_gross_amount")
                        .HasColumnType("double precision");

                    b.Property<double>("total_net_price")
                        .HasColumnType("double precision");

                    b.HasKey("order_id");

                    b.HasIndex("customer_id");

                    b.ToTable("orders", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.OrderLine", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("text");

                    b.Property<int>("lineNum")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("gross_amount")
                        .HasColumnType("double precision");

                    b.Property<string>("item")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<double?>("net_price")
                        .HasColumnType("double precision");

                    b.Property<double>("quantity")
                        .HasColumnType("double precision");

                    b.Property<double>("tax_amount")
                        .HasColumnType("double precision");

                    b.HasKey("orderId", "lineNum");

                    b.ToTable("orderLines", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Role", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("roles", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_role")
                        .HasColumnType("bigint");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_role");

                    b.ToTable("users", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Client", "client")
                        .WithMany("orders")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.OrderLine", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryConnection.DbSet.User", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Role", "Role")
                        .WithMany("users")
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Client", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Role", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
