// <auto-generated />
using System;
using LibraryConnection.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031030857_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryConnection.DbSet.Cart", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("session_token")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("session_token");

                    b.HasIndex("user_id");

                    b.ToTable("carts", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.CartItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<Guid>("cart_id")
                        .HasColumnType("uuid");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<double>("subtotal")
                        .HasColumnType("double precision");

                    b.Property<double>("unit_price")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("cart_id", "product_id")
                        .IsUnique();

                    b.ToTable("cart_items", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("categories", "dev");

                    b.HasData(
                        new
                        {
                            id = 1,
                            is_active = true,
                            name = "Bebidas"
                        },
                        new
                        {
                            id = 2,
                            is_active = true,
                            name = "Snacks"
                        },
                        new
                        {
                            id = 3,
                            is_active = true,
                            name = "Dulces"
                        });
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Client", b =>
                {
                    b.Property<string>("document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("docType")
                        .HasColumnType("text");

                    b.Property<string>("emailAddress")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("document");

                    b.ToTable("clients", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.Property<string>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("customer_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<double>("total_gross_amount")
                        .HasColumnType("double precision");

                    b.Property<double>("total_net_price")
                        .HasColumnType("double precision");

                    b.HasKey("order_id");

                    b.HasIndex("customer_id");

                    b.ToTable("orders", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.OrderLine", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("text");

                    b.Property<int>("lineNum")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("gross_amount")
                        .HasColumnType("double precision");

                    b.Property<string>("item")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<double?>("net_price")
                        .HasColumnType("double precision");

                    b.Property<double>("quantity")
                        .HasColumnType("double precision");

                    b.Property<double>("tax_amount")
                        .HasColumnType("double precision");

                    b.HasKey("orderId", "lineNum");

                    b.ToTable("orderLines", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<int>("stock")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("is_active");

                    b.ToTable("products", "dev");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category_id = 1,
                            description = "Botella de agua",
                            image_url = "https://images.unsplash.com/photo-1548833793-71ad3875f2ac?w=800&q=80",
                            is_active = true,
                            name = "Agua mineral 600ml",
                            price = 1.2,
                            stock = 100
                        },
                        new
                        {
                            id = 2,
                            category_id = 1,
                            description = "Bebida gaseosa",
                            image_url = "https://images.unsplash.com/photo-1623446043588-739e8f6daba1?w=800&q=80",
                            is_active = true,
                            name = "Gaseosa cola 500ml",
                            price = 1.8,
                            stock = 80
                        },
                        new
                        {
                            id = 3,
                            category_id = 1,
                            description = "Sabor naranja",
                            image_url = "https://images.unsplash.com/photo-1542444459-db63c0d2c979?w=800&q=80",
                            is_active = true,
                            name = "Jugo natural 350ml",
                            price = 1.5,
                            stock = 60
                        },
                        new
                        {
                            id = 4,
                            category_id = 2,
                            description = "Snack salado",
                            image_url = "https://images.unsplash.com/photo-1596461404969-9ae70d18e7d5?w=800&q=80",
                            is_active = true,
                            name = "Papitas clásicas 45g",
                            price = 1.0,
                            stock = 120
                        },
                        new
                        {
                            id = 5,
                            category_id = 2,
                            description = "Bolsa de maní",
                            image_url = "https://images.unsplash.com/photo-1601000924815-65f0f41cd3ed?w=800&q=80",
                            is_active = true,
                            name = "Maní salado 50g",
                            price = 0.90000000000000002,
                            stock = 90
                        },
                        new
                        {
                            id = 6,
                            category_id = 2,
                            description = "Con queso",
                            image_url = "https://images.unsplash.com/photo-1604908554049-69a3a9c7f4ec?w=800&q=80",
                            is_active = true,
                            name = "Nachos 70g",
                            price = 1.3,
                            stock = 70
                        },
                        new
                        {
                            id = 7,
                            category_id = 3,
                            description = "70% cacao",
                            image_url = "https://images.unsplash.com/photo-1548907040-4b7d48268e8b?w=800&q=80",
                            is_active = true,
                            name = "Chocolate barra 40g",
                            price = 1.1000000000000001,
                            stock = 50
                        },
                        new
                        {
                            id = 8,
                            category_id = 3,
                            description = "Frutales",
                            image_url = "https://images.unsplash.com/photo-1589712230557-cf5f38f3d001?w=800&q=80",
                            is_active = true,
                            name = "Gomitas 90g",
                            price = 0.94999999999999996,
                            stock = 65
                        },
                        new
                        {
                            id = 9,
                            category_id = 3,
                            description = "Mix sabores",
                            image_url = "https://images.unsplash.com/photo-1581323361970-989d7a9b6eb9?w=800&q=80",
                            is_active = true,
                            name = "Caramelos surtidos 100g",
                            price = 0.84999999999999998,
                            stock = 150
                        });
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Role", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("roles", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_role")
                        .HasColumnType("bigint");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_role");

                    b.ToTable("users", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.CartItem", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Cart", "Cart")
                        .WithMany("items")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryConnection.DbSet.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Client", "client")
                        .WithMany("orders")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.OrderLine", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Product", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.User", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Role", "Role")
                        .WithMany("users")
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Cart", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Client", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Role", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
