// <auto-generated />
using System;
using LibraryConnection.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryConnection.DbSet.Cart", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("session_token")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("session_token");

                    b.HasIndex("user_id");

                    b.ToTable("carts", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.CartItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<Guid>("cart_id")
                        .HasColumnType("uuid");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<double>("subtotal")
                        .HasColumnType("double precision");

                    b.Property<double>("unit_price")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("cart_id", "product_id")
                        .IsUnique();

                    b.ToTable("cart_items", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("categories", "dev");

                    b.HasData(
                        new
                        {
                            id = 1,
                            is_active = true,
                            name = "Bebidas"
                        },
                        new
                        {
                            id = 2,
                            is_active = true,
                            name = "Snacks"
                        },
                        new
                        {
                            id = 3,
                            is_active = true,
                            name = "Dulces"
                        });
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Client", b =>
                {
                    b.Property<string>("document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("docType")
                        .HasColumnType("text");

                    b.Property<string>("emailAddress")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("document");

                    b.ToTable("clients", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.Property<string>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("customer_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<double>("total_gross_amount")
                        .HasColumnType("double precision");

                    b.Property<double>("total_net_price")
                        .HasColumnType("double precision");

                    b.HasKey("order_id");

                    b.HasIndex("customer_id");

                    b.ToTable("orders", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.OrderLine", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("text");

                    b.Property<int>("lineNum")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("gross_amount")
                        .HasColumnType("double precision");

                    b.Property<string>("item")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<double?>("net_price")
                        .HasColumnType("double precision");

                    b.Property<double>("quantity")
                        .HasColumnType("double precision");

                    b.Property<double>("tax_amount")
                        .HasColumnType("double precision");

                    b.HasKey("orderId", "lineNum");

                    b.ToTable("orderLines", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<int>("stock")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("is_active");

                    b.ToTable("products", "dev");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category_id = 1,
                            description = "Botella de agua",
                            image_url = "https://images.unsplash.com/photo-1637774139107-b83aae618551?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=735",
                            is_active = true,
                            name = "Agua mineral 600ml",
                            price = 2000.0,
                            stock = 100
                        },
                        new
                        {
                            id = 2,
                            category_id = 1,
                            description = "Bebida gaseosa",
                            image_url = "https://images.unsplash.com/photo-1622708862830-a026e3ef60bd?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=682",
                            is_active = true,
                            name = "Gaseosa cola 500ml",
                            price = 2500.0,
                            stock = 80
                        },
                        new
                        {
                            id = 3,
                            category_id = 1,
                            description = "Sabor naranja",
                            image_url = "https://images.unsplash.com/photo-1621506289894-c3a62d6be8f3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687",
                            is_active = true,
                            name = "Jugo natural 350ml",
                            price = 2200.0,
                            stock = 60
                        },
                        new
                        {
                            id = 4,
                            category_id = 2,
                            description = "Snack salado",
                            image_url = "https://images.unsplash.com/photo-1741520150134-0d60d82dfac9?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1406",
                            is_active = true,
                            name = "Papitas clásicas 45g",
                            price = 1800.0,
                            stock = 120
                        },
                        new
                        {
                            id = 5,
                            category_id = 2,
                            description = "Bolsa de maní",
                            image_url = "https://www.istockphoto.com/photo/roasted-salted-peanuts-in-bowl-on-wooden-table-gm2208003368-625205923?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_bottom&utm_content=https%3A%2F%2Funsplash.com%2Fes%2Fs%2Ffotos%2Froasted-peanuts-salted&utm_term=roasted+peanuts+salted%3A%3Alayout-below-fold-units-2%3Acontrol",
                            is_active = true,
                            name = "Maní salado 50g",
                            price = 1500.0,
                            stock = 90
                        },
                        new
                        {
                            id = 6,
                            category_id = 2,
                            description = "Con queso",
                            image_url = "https://unsplash.com/es/fotos/una-pizza-con-verduras-y-queso-RV4-buXKOS8",
                            is_active = true,
                            name = "Nachos 70g",
                            price = 2300.0,
                            stock = 70
                        },
                        new
                        {
                            id = 7,
                            category_id = 3,
                            description = "70% cacao",
                            image_url = "https://unsplash.com/es/fotos/barra-de-chocolate-hersheys-sobre-superficie-blanca-7pvYgmkqOzc",
                            is_active = true,
                            name = "Chocolate barra 40g",
                            price = 2000.0,
                            stock = 50
                        },
                        new
                        {
                            id = 8,
                            category_id = 3,
                            description = "Frutales",
                            image_url = "https://unsplash.com/es/fotos/un-monton-de-caramelos-de-diferentes-colores-sobre-una-superficie-azul-1hRz-_MIwbk",
                            is_active = true,
                            name = "Gomitas 90g",
                            price = 1600.0,
                            stock = 65
                        },
                        new
                        {
                            id = 9,
                            category_id = 3,
                            description = "Bandeja de cupcakes",
                            image_url = "https://media.istockphoto.com/id/171360702/es/foto/vista-a%C3%A9rea-de-la-bandeja-con-cupcakes.webp?a=1&b=1&s=612x612&w=0&k=20&c=y9htsC84M1g1lu03oQYNBMIWqxMmWQr9_T7nGdk8hvA=",
                            is_active = true,
                            name = "Cupcakes surtidos",
                            price = 1800.0,
                            stock = 40
                        });
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Role", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("roles", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_role")
                        .HasColumnType("bigint");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_role");

                    b.ToTable("users", "dev");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.CartItem", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Cart", "Cart")
                        .WithMany("items")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryConnection.DbSet.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Client", "client")
                        .WithMany("orders")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.OrderLine", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Product", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.User", b =>
                {
                    b.HasOne("LibraryConnection.DbSet.Role", "Role")
                        .WithMany("users")
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Cart", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Client", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("LibraryConnection.DbSet.Role", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
